import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Page from "../components/Page";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <section>
          <div className="bg-indigo-700">
            <div className="mx-auto max-w-2xl py-16 px-4 text-center sm:py-20 sm:px-6 lg:px-8">
              <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
                <span className="block">
                  Welcome to Pok3r Network, a multiplayer, on-chain
                  decentralized poker room.
                </span>
                {/* <span className="block">Start using our app today.</span> */}
              </h2>
              <p className="mt-4 text-lg leading-6 text-indigo-200">
                Ac euismod vel sit maecenas id pellentesque eu sed consectetur.
                Malesuada adipiscing sagittis vel nulla nec.
              </p>
              <a
                href="#"
                className="mt-8 inline-flex w-full items-center justify-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-indigo-600 hover:bg-indigo-50 sm:w-auto"
              >
                Launch app
              </a>
            </div>
          </div>
        </section>
        <section>
          <div className="overflow-hidden bg-white py-16 px-4 sm:px-6 lg:px-8 xl:py-36">
            <div className="mx-auto max-w-max lg:max-w-7xl">
              <div className="relative z-10 mb-8 md:mb-2 md:px-6">
                <div className="max-w-prose text-base lg:max-w-none">
                  <h2 className="font-semibold leading-6 text-indigo-600">
                    How Pok3r Network Works
                  </h2>
                  <p className="mt-2 text-3xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl">
                    A better way to play poker.
                  </p>
                </div>
              </div>
              <div className="relative">
                <div className="relative md:bg-white md:p-6">
                  <div className="lg:grid lg:grid-cols-2 lg:gap-6">
                    <div className="prose prose-lg prose-indigo text-gray-500 lg:max-w-none">
                      <p>
                        Ultrices ultricies a in odio consequat egestas rutrum.
                        Ut vitae aliquam in ipsum. Duis nullam placerat cursus
                        risus ultrices nisi, vitae tellus in. Qui non fugiat aut
                        minus aut rerum. Perspiciatis iusto mollitia iste minima
                        soluta id.
                      </p>
                      <p>
                        Erat pellentesque dictumst ligula porttitor risus eget
                        et eget. Ultricies tellus felis id dignissim eget. Est
                        augue <a href="#">maecenas</a> risus nulla ultrices
                        congue nunc tortor. Eu leo risus porta integer
                        suspendisse sed sit ligula elit.
                      </p>
                      <ol role="list">
                        <li>
                          Integer varius imperdiet sed interdum felis cras in
                          nec nunc.
                        </li>
                        <li>
                          Quam malesuada odio ut sit egestas. Elementum at porta
                          vitae.
                        </li>
                      </ol>
                      <p>
                        Amet, eu nulla id molestie quis tortor. Auctor erat
                        justo, sed pellentesque scelerisque interdum blandit
                        lectus. Nec viverra amet ac facilisis vestibulum.
                        Vestibulum purus nibh ac ultricies congue.
                      </p>
                    </div>
                    <div className="prose prose-lg prose-indigo mt-6 text-gray-500 lg:mt-0">
                      <p>
                        Erat pellentesque dictumst ligula porttitor risus eget
                        et eget. Ultricies tellus felis id dignissim eget. Est
                        augue maecenas risus nulla ultrices congue nunc tortor.
                      </p>
                      <p>
                        Eu leo risus porta integer suspendisse sed sit ligula
                        elit. Elit egestas lacinia sagittis pellentesque neque
                        dignissim vulputate sodales. Diam sed mauris felis
                        risus, ultricies mauris netus tincidunt. Mauris sit eu
                        ac tellus nibh non eget sed accumsan. Viverra ac sed
                        venenatis pulvinar elit. Cras diam quis tincidunt
                        lectus. Non mi vitae, scelerisque felis nisi, netus amet
                        nisl.
                      </p>
                      <p>
                        Eu eu mauris bibendum scelerisque adipiscing et. Justo,
                        elementum consectetur morbi eros, posuere ipsum tortor.
                        Eget cursus massa sed velit feugiat sed ut. Faucibus
                        eros mauris morbi aliquam nullam. Scelerisque elementum
                        sit magna ullamcorper dignissim pretium.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Page>
    </div>
  );
}
